version: "3"

services:
  influxdb:
    build: ./influxdb
    container_name: local-influxdb #grafanaからアクセスするための名前
    volumes:
      - ./influxdb/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083

  grafana:
    build: ./grafana
    ports:
      - 3000:3000 #grafanaのポート
    user: "472"
    volumes:
      - ./grafana/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    tty: true
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}

  mysql:
    image: mysql:8.0.31-debian
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/db.cnf:/etc/mysql/conf.d/my.cnf
    tty: true

  jenkins:
    build: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/host_working/infra
      - ~/develop:/host_working/develop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    tty: true

volumes:
  db-store:
