version: "2"

services:
  influxdb:
    image: influxdb
    container_name: local-influxdb #grafanaからアクセスするための名前
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083

  grafana:
    image: grafana/grafana:main-ubuntu
    ports:
      - 8085:3000 #grafanaのポート
    user: "472"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - influxdb
    tty: true
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/db.cnf:/etc/mysql/conf.d/my.cnf
    tty: true
volumes:
  db-store:
